### ISSUE TITLE
EP01FE01US02 - visualizar alocação

### ISSUE THREAD

**Issue by VinyPinheiro** [fga-gpp-mds/2017.1-SIGS#25]
User Story:
Eu, como usuário desejo visualizar o que está alocado em um determinado horário com a finalidade de ter conhecimento sobre a atividade corrente naquele horário.

Critérios de Aceitação:

* O usuário deve estar logado;
* Se a alocação for um projeto de extensão deve ser exibido o projeto de extensão, o responśavel, o número de vagas e a periodicidade do projeto;
* Se a alocação for uma turma deve ser exibido a turma, a disciplina, o departamento, número de vagas, cursos associados e recursos exigidos para a turma;
* Deve ser exibido todos os horários e dias relacionados a aquele projeto/turma;
* Se houver mais de uma turma associada a alocação, todas devem ser exibidas.

**Comment by vinisilvacar** [comment]
Protótipo:
Ativo: Sim -> Recomendo mudar para: "Status: Ativo"

Categorias: -> Recomendo mudar para "Recursos"

* Alocação de Turma: 
       - não aparece o departamento da turma

* Alocação de Extensão: 
       - não tem exemplo de alocação de extensão
