### ISSUE TITLE
EP01FE03US15 - Gerar relatórios de alocação por prédio

### ISSUE THREAD

**Issue by danielmarques28** [fga-gpp-mds/2017.1-SIGS#54]
Descrição da US:
* Eu como coordenação ou PRC desejo gerar um relatório de alocação por prédio, com o objetivo de divulgar quais alocações estão ocorrendo nas salas de um determinado prédio.

Critérios de Aceitação:
* O relatório deve ser gerado em PDF.
* O usuário PRC pode gerar o relatório de qualquer prédio.
* O usuário coordenação pode gerar relatórios apenas referente ao seu prédio do seu departamento.

**Comment by vinisilvacar** [comment]
O Prédio possui 3 atributos (código, nome e ala). 

Acho interessante colocar o Código e o Nome, com isso, a pesquisa também poderá ser por código ou nome (pode ser apenas um campo de pesquisa e consiga encontrar pelos dois tipos de entrada).

Ao gerar o PDF, confirme o fechamento da tabela (linha vertical a esquerda).
